<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>KonoplevWPF</RootNamespace>
    <AssemblyName>KonoplevWPF</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KonoplevLibraryFramework\KonoplevLibraryFramework.csproj" />
  </ItemGroup>
</Project>

